name: Stylelint

on:
  pull_request:
    branches: [ main ]

jobs:
  stylelint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install --include=dev

    - name: Run Stylelint
      run: npx stylelint "**/*.css"
